### ISSUE TITLE
Agendar reunión con André para hablar de Conected Devices: 5 de diciembre

### ISSUE THREAD

**Issue by danysriot** [danysriot/Equal-Rating#10]
@yulireyji hablará con André, un colaborador de Brasil dentro del proyecto de Conected Devices de Mozilla, para agendar una reunión por videoconferencia para que nos cuente más del proyecto, el cómo lo lleva a cabo y con qué tipo de tecnología, esto para nutrir nuestro proyecto y ver si podemos usar algunas de las cosas ya existentes en iOT para incluirlo en nuestro pitch.

La reunión tendría que estar agendada para este lunes 5 para que nos dé tiempo de empatar agendas y ver si @BoSicle se podrá conectar desde Hawaii. Bob, ¿podrías decirnos cuál es tu disponibilidad de horarios?

**Comment by siclemx** [comment]
Al parecer André no podrá apoyarnos con este tema. Me dice que no está muy familiarizado con el funcionamiento de Firefox OS sin Gaia o bien de Jan OS o las chirimen.
