### ISSUE TITLE
Sebastian comparte información sobre el proyecto de monitoreo forestal: 3 Diciembre

### ISSUE THREAD

**Issue by danysriot** [danysriot/Equal-Rating#2]
@penserbjorne mencionó que tiene información que podría sernos útil sobre un proyecto que usó celulares conectados para monitorear la tala ilegal en una zona del paìs. 

Los links, videos o documentaciòn se compartiràn antes del 3 de diciembre para que todos podamos leerlos y retroalimentar la idea.

**Comment by penserbjorne** [comment]
Lo que les comentaba de tala ilegal no fue aqui, fue en otro pais, es una charla de TED, les dejo los enlaces aqui abajo, igual buscare si hay mas info disponible del proyecto.
- [Video de la charla en TED](http://www.ted.com/talks/topher_white_what_can_save_the_rainforest_your_used_cell_phone)
- [Texto del video](https://www.ted.com/talks/topher_white_what_can_save_the_rainforest_your_used_cell_phone/transcript?language=es)

Creo que seria bueno leer los comentarios, tal vez ahi venga mas informacion.
