### ISSUE TITLE
Sebas comparte tutoriales o informaciòn para usar mejor Github: 2 de Diciembre

### ISSUE THREAD

**Issue by danysriot** [danysriot/Equal-Rating#3]
@penserbjorne compartirá información útil a Daniela, que ayude a mejorar la gestión del proyecto a través de Github.

La información tendrá que enviarse antes del 2 de diciembre.

**Comment by penserbjorne** [comment]
Te dejo lo de markdown para que le puedas dar mas formato a los issues y .md (como el README.md)
- [Lo basico de markdown](https://guides.github.com/features/mastering-markdown/)
- [Guia ya mas completa de markdown](https://help.github.com/categories/writing-on-github/)
- [Emojis :3](http://www.webpagefx.com/tools/emoji-cheat-sheet/)

Esto son las practicas ''basicas'' para trabajar con repos, checalo, son cuatro practicas, son de una clase que tome, te recomiendo que las pruebes con el repo de alguien mas o de un proyecto que te interese.
- [Practicas de git por Wolf](https://github.com/gwolf/clase-sistop-2017-01/tree/master/practicas)

Si necesitas algo mas avisame , si no marca como cerrado el issue ;)
