### ISSUE TITLE
Investigar población de Tehuacán Puebla: 7 de diciembre

### ISSUE THREAD

**Issue by danysriot** [danysriot/Equal-Rating#4]
@BoSicle investigará los demográficos de Tehuacán Puebla con miras a hacer de esta localidad el punto central de acceso en la zona. 

Si este lugar seria el punto central y lo enfocaremos un poco a educación ahí, investigar el número de escuelas, la calidad de la educación en la zona, así como necesidades específicas en el tema sería genial.

La actividad tendría que estar lista para el 7 de diciembre, un día antes de nuestra reunión semanal.

**Comment by siclemx** [comment]
El sábado tengo ya la info.
