### ISSUE TITLE
Tareas para todos a realizarse antes del 5 de diciembre

### ISSUE THREAD

**Issue by danysriot** [danysriot/Equal-Rating#7]
Aquí algunas tareas que nos tocan a todos y que tienen que realizarse para antes del 5 de diciembre, para que podamos comentar las tareas y generar un poco de discusión previa a nuestra junta semana

- El primer webinar del concurso ha pasado y tenemos que ponernos al día viendo el video en Air Mozilla. Aquí está el link: https://air.mozilla.org/webinar-2-what-is-equal-rating/ el tema del webinar es: ¿Qué es Equal Rating? El idioma es inglés.
- Queremos integrar temas de educación para ofrecer al punto central de acceso, para que los niños se nutran de los datos que estemos generando y conozcan más del lugar donde viven. La tarea es pensar ¿Qué temas en educación se les ocurre que podemos ofrecer basados en el tipo de datos que obtendremos del monitoreo? (temperatura, humedad, geolocalización, movimiento del suelo y cualquier cosa que pueda medir el sensor de un celular) 

@KuronekoKat @penserbjorne Yulianna estaría genial que pusieran sus comentarios sobre el webinar y las ideas que tengan del segundo punto en los comentarios.

**Comment by siclemx** [comment]
Ya hay otro webinar, y estuvo bastante interesante les dejo el enlace https://air.mozilla.org/webinar-3-your-equal-rating-questions-answered/ creo que vamos por la dirección correcta y tenemos una buena idea ya solo es limar los detalles técnicos y lo de porque esa zona ya que hay que orientarlo bien ya que como dicen lo de la infraestructura y lo que sabe y puede hacer un usuario se podria malinterpretar y decir que "no fuimos por lo facíl"y listo.
